cargo-features = ["strip"]

[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
default-run = "app"
edition = "2018"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = "1.0.0-beta.4"

[dependencies]
serde_json = "1.0.68"
serde = { version = "1.0.130", features = ["derive"] }
tauri = { version = "1.0.0-beta.8", features = ["api-all"] }
cfg-if = "1.0.0"
directories-next = "2.0.0"
once_cell = "1.8.0"
load-dotenv = "0.1.2"
interprocess = "1.1.1"
tauri-plugin-store = { git = "https://github.com/tauri-apps/tauri-plugin-store" }

[patch.crates-io]
tauri = { git = "https://github.com/tauri-apps/tauri", branch = "next" }
wry = { git = "https://github.com/tauri-apps/wry", branch = "next" }

[features]
default = ["custom-protocol", "tauri/api-all"]
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"
strip = true
